[package]
name = "gaussian"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/gaussian"
homepage = "https://github.com/hilbert-space/gaussian"
description = "Gaussian."
